KIND=binary
GITHUB=Quad4-Software/Ren-Browser
TAG=v0.3.0
ARCHES="x86_64 aarch64"
ASSET_x86_64=renbrowser-linux-amd64
ASSET_aarch64=renbrowser-linux-arm64
SOURCE_TARBALL=1
CONFLICTS=
PROVIDES=renbrowser
VERIFY=sha256sums
SHA256SUMS=SHA256SUMS.txt
