REPO_NAME=quad4
REPO_MAINTAINER='Quad4.io <ivan@quad4.io>'
REPO_PACKAGER='Quad4 Packaging <packages@quad4.io>'
REPO_GPGKEY='97B937E980BDD9C89F06D7FA3BCCE6B7FB4AE3B5'
GITHUB_ORG=Quad4-Software
GITHUB_REPO=arch
PAGES_URL=https://arch.quad4.io
RELEASE_PREFIX=pkg
