KIND=binary
GITHUB=Quad4-Software/MeshChatX
TAG=v4.8.5
ARCHES="x86_64 aarch64"
ASSET_x86_64=ReticulumMeshChatX-v@VER@-linux-x86_64.AppImage
ASSET_aarch64=ReticulumMeshChatX-v@VER@-linux-arm64.AppImage
SOURCE_TARBALL=1
CONFLICTS=meshchatx-git
PROVIDES=meshchatx
