KIND=binary
GITHUB=Quad4-Software/Reticulum-Go
TAG=v1.1.1
ASSET_x86_64=reticulum-go-linux-amd64
ASSET_aarch64=reticulum-go-linux-arm64
ASSET_armv7h=reticulum-go-linux-arm
SOURCE_TARBALL=1
CONFLICTS=reticulum-go-git
PROVIDES=reticulum-go
