KIND=binary
GITHUB=Quad4-Software/nullray
TAG=v0.3.0
ARCHES="x86_64 aarch64"
ASSET_x86_64=nullray_@VER@_linux_amd64.tar.gz
ASSET_aarch64=nullray_@VER@_linux_arm64.tar.gz
SOURCE_TARBALL=1
CONFLICTS="nullray-git"
PROVIDES="nullray"
REPLACES="nullray"
VERIFY=none
